### ISSUE TITLE
Software Construction Strategy - No clear idea of non-standard language features

### ISSUE THREAD

**Issue by MartinDLSU** [RedJaguars/Deliverables#17]
In the fourth paragraph of the construction strategy portion, it states that programmers are discouraged to use non-standard language features without defining what these non-standard language features are.

Suggestions: Please give some examples of non-standard language features.

**Comment by DudeGrim** [comment]
Please check the new update.

https://github.com/RedJaguars/Deliverables/commit/3a95c53e5cef19b3129d74c1c64751113a9d3e8d
